[build.environment]
  # bypass npm auto installing
  NPM_FLAGS = "--version"

[build]
  publish = "dist/"
  command = "npx pnpm install --store-dir=node_modules/.pnpm-store && npx pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
