// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICodiconGithubAlt: typeof import('~icons/codicon/github-alt')['default']
    IIonHomeOutline: typeof import('~icons/ion/home-outline')['default']
    IIonIosBolt: typeof import('~icons/ion/ios-bolt')['default']
    IIonIosInformationCircleOutline: typeof import('~icons/ion/ios-information-circle-outline')['default']
    IIonLanguageOutline: typeof import('~icons/ion/language-outline')['default']
    IIonMinus: typeof import('~icons/ion/minus')['default']
    IIonMoonOutline: typeof import('~icons/ion/moon-outline')['default']
    IIonPlus: typeof import('~icons/ion/plus')['default']
    IIonSunnyOutline: typeof import('~icons/ion/sunny-outline')['default']
    ITeenyiconsMarkdownOutline: typeof import('~icons/teenyicons/markdown-outline')['default']
  }
}

export { }
